React capstone project - Metrics webapp
jlcarrascof/React-capstone-project-Metrics-webapp pull request #7
Opened 2023-09-09 18:32 UTC by jlcarrascof

### **Features**

- [ ] Dependencies and libraries installed.
- [ ] Components folder with air pollution items and a detailed (list) of every item.
- [ ] Fetch data from https://openweathermap.org/api/air-pollution
- [ ] File countries items and a list of these items for the home page
- [ ] Europe countries for the API of air pollution parameters
- [ ] Navbar for the navigation bar of the web app using router
- [ ] Search bar on the home page to filter country
- [ ] Back button function in the navbar to return to the home page
- [ ] Detail button in each country to see the air pollution data of that country (Only available in the arrow button, not the entire section).
- [ ] Redux store and DetailSlice for API fetch and search reducers.
- [ ] Jest tests for CountriesItems
- [ ] Graph bar for the values of air in the country details section.
- [ ] Fix Linters
- [ ] Update readme info and deploy and record video.

2023-09-09 20:21 UTC, divinecharlotte requested changes
Hi @jlcarrascof     , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Clean code👍 
- Implemented some project requirements   👍 

 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️


_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-09 20:21 UTC, divinecharlotte commented on src/pages/Navigation.js
> +
- [ ] Kindly consider following the below pattern to make sure you can navigate between pages without reloading.

```javascript
  import { Switch, Route, Redirect } from "react-router-dom";  
  
  [...]

  <Switch>
        <Route exact path="/" component={HomePage} />
        <Route path="/items" component={Items} />
        <Route exact path="/item/:id" component={Item} />
        [...]
   </Switch>     

   [...]
```
and this will make your project  a single page application (SPA)

2023-09-09 20:21 UTC, divinecharlotte commented on src/test/CountriesList.test.js
> +import React from 'react';
- [ ] Kindly consider doing unit tests for several components of the app and some pure functions in Redux code. to meet the project requirement on testing

2023-09-10 02:01 UTC, jlcarrascof reviewed
I created two new tests, dear reviewer:

- [ ] **AirItems.test.js.**
- [ ] **detailSlice.test.js**

2023-09-10 02:10 UTC, jlcarrascof commented on src/pages/Navigation.js
> +
![router](https://github.com/jlcarrascof/React-capstone-project-Metrics-webapp/assets/86327867/3307a30d-70b7-4045-9e0e-edf14f282ed6)

I implemented the changes that you suggested about the pattern of routes to make my project a SPA but in a separate folder in my code (according a video from Internet) and not in the traditional way, but I respected your suggestions as you can see in the image attached.

My apologies but after try to change this structure, my project is giving me errors.

Thanks for your comprehension.

2023-09-10 02:23 UTC, binhussen approved these changes
Hi @jlcarrascof , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Sticked given design ✔️
- Well Stracured Cide✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 13:26 UTC, merged